---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian8_local
    driver:
        box: debian8_local

suites:
  - name: master
    run_list:
      - recipe[platform_jenkins::master]
    attributes:
    driver:
      network:
        - [ 'forwarded_port', { guest: 9080, host: 4290 } ]
        - [ 'private_network', { ip: '192.168.42.200' } ]
  - name: slave
    run_list:
      - recipe[platform_jenkins::slave]
    attributes:
    driver:
      network:
        - [ 'private_network', { ip: '192.168.42.300' } ]