name 'platform_jenkins'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures chef-platform_jenkins'
long_description 'Installs/Configures chef-platform_jenkins'
version '0.2.0'

depends 'platform_base'
depends 'ark'
